baseurl = "https://microBlog.farenew.com/"
languageCode = "zh-CN"
title = "MicroBlog"
hasCJKLanguage = true

theme = "internet-weblog"
# pygmentsstyle = "emacs"
Paginate = 10

[author]
	Handle = "Farenew"
	FirstName = "Farenew"
	# LastName = "Johnson"
	AboutPage = "/about"
	# Location = "Durham, NC"
	# FlickrID = "87151163@N00"

[params]
	Description = "我的微博客"
	ShowCopyright = true
	RSSEnabled = true
	RSSMicropostTitles = false
	mainSections = ["microposts", "photos" ]

[taxonomies]
	tag = "tags"
	category = "categories"
	series = "series"

# [[menu.main]]
# 	name = "Post Archive"
# 	weight = 1
# 	identifier = "posts"
# 	url = "/posts/"

[[menu.main]]
	name = "微博"
	weight = 2
	identifier = "microposts"
	url = "/microposts/"

[[menu.main]]
	name = "照片"
	weight = 3
	identifier = "photos"
	url = "/photos/"