baseurl = "https://jnjosh.com/"
languageCode = "zh-CN"
title = "MicroBlog"
theme = "internet-weblog"
# pygmentsstyle = "emacs"
Paginate = 10

[author]
	Handle = "Farenew"
	# FirstName = ""
	# LastName = "Johnson"
	AboutPage = "/about"
	# Location = "Durham, NC"
	# FlickrID = "87151163@N00"

[params]
	Description = "Internet weblog of Software (Mac, iOS, Web) Developer, Josh Johnson."
	ShowCopyright = true
	RSSEnabled = true
	RSSMicropostTitles = false
	mainSections = [ "posts", "microposts", "photos" ]

[taxonomies]
	tag = "tags"
	category = "categories"
	series = "series"

[[menu.main]]
	name = "Post Archive"
	weight = 1
	identifier = "posts"
	url = "/posts/"

[[menu.main]]
	name = "Photos"
	weight = 2
	identifier = "photos"
	url = "/photos/"